<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/function.proto

namespace GPBMetadata\Proto;

class PBFunction
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
@
proto/function.protoluaBZ/proto blackjack200\\luabproto3'
        , true);

        static::$is_initialized = true;
    }
}

