<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service.proto

namespace blackjack200\lua;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>lua.EvaluateResponse</code>
 */
class EvaluateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string stdout = 1;</code>
     */
    protected $stdout = '';
    /**
     * Generated from protobuf field <code>string stderr = 2;</code>
     */
    protected $stderr = '';
    /**
     * Generated from protobuf field <code>string combineOut = 3;</code>
     */
    protected $combineOut = '';
    /**
     * Generated from protobuf field <code>optional string error = 4;</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stdout
     *     @type string $stderr
     *     @type string $combineOut
     *     @type string $error
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string stdout = 1;</code>
     * @return string
     */
    public function getStdout()
    {
        return $this->stdout;
    }

    /**
     * Generated from protobuf field <code>string stdout = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStdout($var)
    {
        GPBUtil::checkString($var, True);
        $this->stdout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stderr = 2;</code>
     * @return string
     */
    public function getStderr()
    {
        return $this->stderr;
    }

    /**
     * Generated from protobuf field <code>string stderr = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStderr($var)
    {
        GPBUtil::checkString($var, True);
        $this->stderr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string combineOut = 3;</code>
     * @return string
     */
    public function getCombineOut()
    {
        return $this->combineOut;
    }

    /**
     * Generated from protobuf field <code>string combineOut = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCombineOut($var)
    {
        GPBUtil::checkString($var, True);
        $this->combineOut = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string error = 4;</code>
     * @return string
     */
    public function getError()
    {
        return isset($this->error) ? $this->error : '';
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>optional string error = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;

        return $this;
    }

}

